# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QMessageBox
import sys


class Ui_Form(object):

    def setupUi(self, Form):
        Form.resize(350, 516)
        Form.setWindowTitle("下载器")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 311, 31))
        self.lineEdit.setStyleSheet("width: 80px;\n""\n""height: 20px;")
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(20, 80, 71, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(250, 80, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 80, 71, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(20, 150, 301, 351))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Form)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "下载器"))
        self.comboBox.setItemText(0, _translate("Form", "91"))
        self.comboBox.setItemText(1, _translate("Form", "92"))
        self.pushButton.setText(_translate("Form", "提交"))
        self.comboBox_2.setItemText(0, _translate("Form", "嗅探"))
        self.comboBox_2.setItemText(1, _translate("Form", "不嗅探"))


class MyMainForm(QMainWindow, Ui_Form):
    _url_from = '91'
    _is_spider = True
    _href = ''

    def __init__(self, parent=None):
        super(MyMainForm, self).__init__(parent)
        self.setupUi(self)
        self.pushButton.clicked.connect(self.getComboxBoxValue)

    def getComboxBoxValue(self):
        self._url_from = self.comboBox.currentText()
        self._is_spider = self.comboBox_2.currentText()
        self._href = self.lineEdit.text()
        if self._href == '':
            QMessageBox.about(self, "警告", "请输入网址或者视频地址!")
            return






if __name__ == "__main__":
    app = QApplication(sys.argv)
    myWin = MyMainForm()
    myWin.show()
    sys.exit(app.exec_())
